# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rewingchow/ECE1373_assignment2-2021_2017.2_optimized/8v3_shell/pr_region_test_proj/pr_region.srcs/sources_1/bd/pr_region_2/ip/pr_region_2_conv_layer_0_0/pr_region_2_conv_layer_0_0.xci
# IP: The module: 'pr_region_2_conv_layer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rewingchow/ECE1373_assignment2-2021_2017.2_optimized/8v3_shell/pr_region_test_proj/pr_region.srcs/sources_1/bd/pr_region_2/ip/pr_region_2_conv_layer_0_0/constraints/conv_layer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pr_region_2_conv_layer_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/rewingchow/ECE1373_assignment2-2021_2017.2_optimized/8v3_shell/pr_region_test_proj/pr_region.srcs/sources_1/bd/pr_region_2/ip/pr_region_2_conv_layer_0_0/pr_region_2_conv_layer_0_0.xci
# IP: The module: 'pr_region_2_conv_layer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rewingchow/ECE1373_assignment2-2021_2017.2_optimized/8v3_shell/pr_region_test_proj/pr_region.srcs/sources_1/bd/pr_region_2/ip/pr_region_2_conv_layer_0_0/constraints/conv_layer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pr_region_2_conv_layer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
