// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fc_layer.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const int fc_layer::C_S_AXI_DATA_WIDTH = "100000";
const int fc_layer::C_S_AXI_WSTRB_WIDTH = "100";
const int fc_layer::C_S_AXI_ADDR_WIDTH = "100000";
const sc_logic fc_layer::ap_const_logic_1 = sc_dt::Log_1;
const int fc_layer::C_M_AXI_MEM_TARGET_ADDR = "0000000000000000000000000000000000000000000000000000000000000000";
const int fc_layer::C_M_AXI_MEM_USER_VALUE = "0000000000000000000000000000000000000000000000000000000000000000";
const int fc_layer::C_M_AXI_MEM_PROT_VALUE = "0000000000000000000000000000000000000000000000000000000000000000";
const int fc_layer::C_M_AXI_MEM_CACHE_VALUE = "11";
const int fc_layer::C_M_AXI_ID_WIDTH = "1";
const int fc_layer::C_M_AXI_ADDR_WIDTH = "1000000";
const int fc_layer::C_M_AXI_DATA_WIDTH = "100000";
const int fc_layer::C_M_AXI_WSTRB_WIDTH = "100";
const int fc_layer::C_M_AXI_AWUSER_WIDTH = "1";
const int fc_layer::C_M_AXI_ARUSER_WIDTH = "1";
const int fc_layer::C_M_AXI_WUSER_WIDTH = "1";
const int fc_layer::C_M_AXI_RUSER_WIDTH = "1";
const int fc_layer::C_M_AXI_BUSER_WIDTH = "1";
const sc_logic fc_layer::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> fc_layer::ap_const_lv2_0 = "00";
const sc_lv<2> fc_layer::ap_const_lv2_1 = "1";
const bool fc_layer::ap_const_boolean_1 = true;

fc_layer::fc_layer(sc_module_name name) : sc_module(name), mVcdFile(0) {
    fc_layer_CTRL_BUS_s_axi_U = new fc_layer_CTRL_BUS_s_axi<C_S_AXI_CTRL_BUS_ADDR_WIDTH,C_S_AXI_CTRL_BUS_DATA_WIDTH>("fc_layer_CTRL_BUS_s_axi_U");
    fc_layer_CTRL_BUS_s_axi_U->AWVALID(s_axi_CTRL_BUS_AWVALID);
    fc_layer_CTRL_BUS_s_axi_U->AWREADY(s_axi_CTRL_BUS_AWREADY);
    fc_layer_CTRL_BUS_s_axi_U->AWADDR(s_axi_CTRL_BUS_AWADDR);
    fc_layer_CTRL_BUS_s_axi_U->WVALID(s_axi_CTRL_BUS_WVALID);
    fc_layer_CTRL_BUS_s_axi_U->WREADY(s_axi_CTRL_BUS_WREADY);
    fc_layer_CTRL_BUS_s_axi_U->WDATA(s_axi_CTRL_BUS_WDATA);
    fc_layer_CTRL_BUS_s_axi_U->WSTRB(s_axi_CTRL_BUS_WSTRB);
    fc_layer_CTRL_BUS_s_axi_U->ARVALID(s_axi_CTRL_BUS_ARVALID);
    fc_layer_CTRL_BUS_s_axi_U->ARREADY(s_axi_CTRL_BUS_ARREADY);
    fc_layer_CTRL_BUS_s_axi_U->ARADDR(s_axi_CTRL_BUS_ARADDR);
    fc_layer_CTRL_BUS_s_axi_U->RVALID(s_axi_CTRL_BUS_RVALID);
    fc_layer_CTRL_BUS_s_axi_U->RREADY(s_axi_CTRL_BUS_RREADY);
    fc_layer_CTRL_BUS_s_axi_U->RDATA(s_axi_CTRL_BUS_RDATA);
    fc_layer_CTRL_BUS_s_axi_U->RRESP(s_axi_CTRL_BUS_RRESP);
    fc_layer_CTRL_BUS_s_axi_U->BVALID(s_axi_CTRL_BUS_BVALID);
    fc_layer_CTRL_BUS_s_axi_U->BREADY(s_axi_CTRL_BUS_BREADY);
    fc_layer_CTRL_BUS_s_axi_U->BRESP(s_axi_CTRL_BUS_BRESP);
    fc_layer_CTRL_BUS_s_axi_U->ACLK(ap_clk);
    fc_layer_CTRL_BUS_s_axi_U->ARESET(ap_rst_n_inv);
    fc_layer_CTRL_BUS_s_axi_U->ACLK_EN(ap_var_for_const0);
    fc_layer_CTRL_BUS_s_axi_U->ap_start(ap_start);
    fc_layer_CTRL_BUS_s_axi_U->interrupt(interrupt);
    fc_layer_CTRL_BUS_s_axi_U->ap_ready(ap_ready);
    fc_layer_CTRL_BUS_s_axi_U->ap_done(ap_done);
    fc_layer_CTRL_BUS_s_axi_U->ap_idle(ap_idle);
    fc_layer_CTRL_BUS_s_axi_U->input_offset(input_offset);
    fc_layer_CTRL_BUS_s_axi_U->output_offset(output_offset);
    fc_layer_CTRL_BUS_s_axi_U->batch_size(batch_size);
    fc_layer_CTRL_BUS_s_axi_U->num_inputs(num_inputs);
    fc_layer_CTRL_BUS_s_axi_U->num_outputs(num_outputs);
    fc_layer_CTRL_BUS_s_axi_U->enable_relu(enable_relu);
    fc_layer_mem_m_axi_U = new fc_layer_mem_m_axi<32,64,5,16,16,16,16,C_M_AXI_MEM_ID_WIDTH,C_M_AXI_MEM_ADDR_WIDTH,C_M_AXI_MEM_DATA_WIDTH,C_M_AXI_MEM_AWUSER_WIDTH,C_M_AXI_MEM_ARUSER_WIDTH,C_M_AXI_MEM_WUSER_WIDTH,C_M_AXI_MEM_RUSER_WIDTH,C_M_AXI_MEM_BUSER_WIDTH,C_M_AXI_MEM_TARGET_ADDR,C_M_AXI_MEM_USER_VALUE,C_M_AXI_MEM_PROT_VALUE,C_M_AXI_MEM_CACHE_VALUE>("fc_layer_mem_m_axi_U");
    fc_layer_mem_m_axi_U->AWVALID(m_axi_mem_AWVALID);
    fc_layer_mem_m_axi_U->AWREADY(m_axi_mem_AWREADY);
    fc_layer_mem_m_axi_U->AWADDR(m_axi_mem_AWADDR);
    fc_layer_mem_m_axi_U->AWID(m_axi_mem_AWID);
    fc_layer_mem_m_axi_U->AWLEN(m_axi_mem_AWLEN);
    fc_layer_mem_m_axi_U->AWSIZE(m_axi_mem_AWSIZE);
    fc_layer_mem_m_axi_U->AWBURST(m_axi_mem_AWBURST);
    fc_layer_mem_m_axi_U->AWLOCK(m_axi_mem_AWLOCK);
    fc_layer_mem_m_axi_U->AWCACHE(m_axi_mem_AWCACHE);
    fc_layer_mem_m_axi_U->AWPROT(m_axi_mem_AWPROT);
    fc_layer_mem_m_axi_U->AWQOS(m_axi_mem_AWQOS);
    fc_layer_mem_m_axi_U->AWREGION(m_axi_mem_AWREGION);
    fc_layer_mem_m_axi_U->AWUSER(m_axi_mem_AWUSER);
    fc_layer_mem_m_axi_U->WVALID(m_axi_mem_WVALID);
    fc_layer_mem_m_axi_U->WREADY(m_axi_mem_WREADY);
    fc_layer_mem_m_axi_U->WDATA(m_axi_mem_WDATA);
    fc_layer_mem_m_axi_U->WSTRB(m_axi_mem_WSTRB);
    fc_layer_mem_m_axi_U->WLAST(m_axi_mem_WLAST);
    fc_layer_mem_m_axi_U->WID(m_axi_mem_WID);
    fc_layer_mem_m_axi_U->WUSER(m_axi_mem_WUSER);
    fc_layer_mem_m_axi_U->ARVALID(m_axi_mem_ARVALID);
    fc_layer_mem_m_axi_U->ARREADY(m_axi_mem_ARREADY);
    fc_layer_mem_m_axi_U->ARADDR(m_axi_mem_ARADDR);
    fc_layer_mem_m_axi_U->ARID(m_axi_mem_ARID);
    fc_layer_mem_m_axi_U->ARLEN(m_axi_mem_ARLEN);
    fc_layer_mem_m_axi_U->ARSIZE(m_axi_mem_ARSIZE);
    fc_layer_mem_m_axi_U->ARBURST(m_axi_mem_ARBURST);
    fc_layer_mem_m_axi_U->ARLOCK(m_axi_mem_ARLOCK);
    fc_layer_mem_m_axi_U->ARCACHE(m_axi_mem_ARCACHE);
    fc_layer_mem_m_axi_U->ARPROT(m_axi_mem_ARPROT);
    fc_layer_mem_m_axi_U->ARQOS(m_axi_mem_ARQOS);
    fc_layer_mem_m_axi_U->ARREGION(m_axi_mem_ARREGION);
    fc_layer_mem_m_axi_U->ARUSER(m_axi_mem_ARUSER);
    fc_layer_mem_m_axi_U->RVALID(m_axi_mem_RVALID);
    fc_layer_mem_m_axi_U->RREADY(m_axi_mem_RREADY);
    fc_layer_mem_m_axi_U->RDATA(m_axi_mem_RDATA);
    fc_layer_mem_m_axi_U->RLAST(m_axi_mem_RLAST);
    fc_layer_mem_m_axi_U->RID(m_axi_mem_RID);
    fc_layer_mem_m_axi_U->RUSER(m_axi_mem_RUSER);
    fc_layer_mem_m_axi_U->RRESP(m_axi_mem_RRESP);
    fc_layer_mem_m_axi_U->BVALID(m_axi_mem_BVALID);
    fc_layer_mem_m_axi_U->BREADY(m_axi_mem_BREADY);
    fc_layer_mem_m_axi_U->BRESP(m_axi_mem_BRESP);
    fc_layer_mem_m_axi_U->BID(m_axi_mem_BID);
    fc_layer_mem_m_axi_U->BUSER(m_axi_mem_BUSER);
    fc_layer_mem_m_axi_U->ACLK(ap_clk);
    fc_layer_mem_m_axi_U->ARESET(ap_rst_n_inv);
    fc_layer_mem_m_axi_U->ACLK_EN(ap_var_for_const0);
    fc_layer_mem_m_axi_U->I_ARVALID(Loop_batch_loop_proc_U0_m_axi_mem_ARVALID);
    fc_layer_mem_m_axi_U->I_ARREADY(mem_ARREADY);
    fc_layer_mem_m_axi_U->I_ARADDR(Loop_batch_loop_proc_U0_m_axi_mem_ARADDR);
    fc_layer_mem_m_axi_U->I_ARID(Loop_batch_loop_proc_U0_m_axi_mem_ARID);
    fc_layer_mem_m_axi_U->I_ARLEN(Loop_batch_loop_proc_U0_m_axi_mem_ARLEN);
    fc_layer_mem_m_axi_U->I_ARSIZE(Loop_batch_loop_proc_U0_m_axi_mem_ARSIZE);
    fc_layer_mem_m_axi_U->I_ARLOCK(Loop_batch_loop_proc_U0_m_axi_mem_ARLOCK);
    fc_layer_mem_m_axi_U->I_ARCACHE(Loop_batch_loop_proc_U0_m_axi_mem_ARCACHE);
    fc_layer_mem_m_axi_U->I_ARQOS(Loop_batch_loop_proc_U0_m_axi_mem_ARQOS);
    fc_layer_mem_m_axi_U->I_ARPROT(Loop_batch_loop_proc_U0_m_axi_mem_ARPROT);
    fc_layer_mem_m_axi_U->I_ARUSER(Loop_batch_loop_proc_U0_m_axi_mem_ARUSER);
    fc_layer_mem_m_axi_U->I_ARBURST(Loop_batch_loop_proc_U0_m_axi_mem_ARBURST);
    fc_layer_mem_m_axi_U->I_ARREGION(Loop_batch_loop_proc_U0_m_axi_mem_ARREGION);
    fc_layer_mem_m_axi_U->I_RVALID(mem_RVALID);
    fc_layer_mem_m_axi_U->I_RREADY(Loop_batch_loop_proc_U0_m_axi_mem_RREADY);
    fc_layer_mem_m_axi_U->I_RDATA(mem_RDATA);
    fc_layer_mem_m_axi_U->I_RID(mem_RID);
    fc_layer_mem_m_axi_U->I_RUSER(mem_RUSER);
    fc_layer_mem_m_axi_U->I_RRESP(mem_RRESP);
    fc_layer_mem_m_axi_U->I_RLAST(mem_RLAST);
    fc_layer_mem_m_axi_U->I_AWVALID(Loop_batch_loop_proc_U0_m_axi_mem_AWVALID);
    fc_layer_mem_m_axi_U->I_AWREADY(mem_AWREADY);
    fc_layer_mem_m_axi_U->I_AWADDR(Loop_batch_loop_proc_U0_m_axi_mem_AWADDR);
    fc_layer_mem_m_axi_U->I_AWID(Loop_batch_loop_proc_U0_m_axi_mem_AWID);
    fc_layer_mem_m_axi_U->I_AWLEN(Loop_batch_loop_proc_U0_m_axi_mem_AWLEN);
    fc_layer_mem_m_axi_U->I_AWSIZE(Loop_batch_loop_proc_U0_m_axi_mem_AWSIZE);
    fc_layer_mem_m_axi_U->I_AWLOCK(Loop_batch_loop_proc_U0_m_axi_mem_AWLOCK);
    fc_layer_mem_m_axi_U->I_AWCACHE(Loop_batch_loop_proc_U0_m_axi_mem_AWCACHE);
    fc_layer_mem_m_axi_U->I_AWQOS(Loop_batch_loop_proc_U0_m_axi_mem_AWQOS);
    fc_layer_mem_m_axi_U->I_AWPROT(Loop_batch_loop_proc_U0_m_axi_mem_AWPROT);
    fc_layer_mem_m_axi_U->I_AWUSER(Loop_batch_loop_proc_U0_m_axi_mem_AWUSER);
    fc_layer_mem_m_axi_U->I_AWBURST(Loop_batch_loop_proc_U0_m_axi_mem_AWBURST);
    fc_layer_mem_m_axi_U->I_AWREGION(Loop_batch_loop_proc_U0_m_axi_mem_AWREGION);
    fc_layer_mem_m_axi_U->I_WVALID(Loop_batch_loop_proc_U0_m_axi_mem_WVALID);
    fc_layer_mem_m_axi_U->I_WREADY(mem_WREADY);
    fc_layer_mem_m_axi_U->I_WDATA(Loop_batch_loop_proc_U0_m_axi_mem_WDATA);
    fc_layer_mem_m_axi_U->I_WID(Loop_batch_loop_proc_U0_m_axi_mem_WID);
    fc_layer_mem_m_axi_U->I_WUSER(Loop_batch_loop_proc_U0_m_axi_mem_WUSER);
    fc_layer_mem_m_axi_U->I_WLAST(Loop_batch_loop_proc_U0_m_axi_mem_WLAST);
    fc_layer_mem_m_axi_U->I_WSTRB(Loop_batch_loop_proc_U0_m_axi_mem_WSTRB);
    fc_layer_mem_m_axi_U->I_BVALID(mem_BVALID);
    fc_layer_mem_m_axi_U->I_BREADY(Loop_batch_loop_proc_U0_m_axi_mem_BREADY);
    fc_layer_mem_m_axi_U->I_BRESP(mem_BRESP);
    fc_layer_mem_m_axi_U->I_BID(mem_BID);
    fc_layer_mem_m_axi_U->I_BUSER(mem_BUSER);
    Block_proc4_U0 = new Block_proc4("Block_proc4_U0");
    Block_proc4_U0->ap_clk(ap_clk);
    Block_proc4_U0->ap_rst(ap_rst_n_inv);
    Block_proc4_U0->ap_start(Block_proc4_U0_ap_start);
    Block_proc4_U0->ap_done(Block_proc4_U0_ap_done);
    Block_proc4_U0->ap_continue(Block_proc4_U0_ap_continue);
    Block_proc4_U0->ap_idle(Block_proc4_U0_ap_idle);
    Block_proc4_U0->ap_ready(Block_proc4_U0_ap_ready);
    Block_proc4_U0->num_outputs(num_outputs);
    Block_proc4_U0->num_inputs(num_inputs);
    Block_proc4_U0->input_offset(input_offset);
    Block_proc4_U0->enable_relu(enable_relu);
    Block_proc4_U0->output_offset(output_offset);
    Block_proc4_U0->batch_size(batch_size);
    Block_proc4_U0->num_outputs_out_din(Block_proc4_U0_num_outputs_out_din);
    Block_proc4_U0->num_outputs_out_full_n(num_outputs_channel_full_n);
    Block_proc4_U0->num_outputs_out_write(Block_proc4_U0_num_outputs_out_write);
    Block_proc4_U0->num_inputs_out_din(Block_proc4_U0_num_inputs_out_din);
    Block_proc4_U0->num_inputs_out_full_n(num_inputs_channel_full_n);
    Block_proc4_U0->num_inputs_out_write(Block_proc4_U0_num_inputs_out_write);
    Block_proc4_U0->batch_size_out_din(Block_proc4_U0_batch_size_out_din);
    Block_proc4_U0->batch_size_out_full_n(batch_size_channel_full_n);
    Block_proc4_U0->batch_size_out_write(Block_proc4_U0_batch_size_out_write);
    Block_proc4_U0->ap_return_0(Block_proc4_U0_ap_return_0);
    Block_proc4_U0->ap_return_1(Block_proc4_U0_ap_return_1);
    Block_proc4_U0->ap_return_2(Block_proc4_U0_ap_return_2);
    Block_proc4_U0->ap_return_3(Block_proc4_U0_ap_return_3);
    Block_proc4_U0->ap_return_4(Block_proc4_U0_ap_return_4);
    Loop_batch_loop_proc_U0 = new Loop_batch_loop_proc("Loop_batch_loop_proc_U0");
    Loop_batch_loop_proc_U0->ap_clk(ap_clk);
    Loop_batch_loop_proc_U0->ap_rst(ap_rst_n_inv);
    Loop_batch_loop_proc_U0->ap_start(Loop_batch_loop_proc_U0_ap_start);
    Loop_batch_loop_proc_U0->ap_done(Loop_batch_loop_proc_U0_ap_done);
    Loop_batch_loop_proc_U0->ap_continue(Loop_batch_loop_proc_U0_ap_continue);
    Loop_batch_loop_proc_U0->ap_idle(Loop_batch_loop_proc_U0_ap_idle);
    Loop_batch_loop_proc_U0->ap_ready(Loop_batch_loop_proc_U0_ap_ready);
    Loop_batch_loop_proc_U0->batch_size_dout(batch_size_channel_dout);
    Loop_batch_loop_proc_U0->batch_size_empty_n(batch_size_channel_empty_n);
    Loop_batch_loop_proc_U0->batch_size_read(Loop_batch_loop_proc_U0_batch_size_read);
    Loop_batch_loop_proc_U0->num_outputs_dout(num_outputs_channel_dout);
    Loop_batch_loop_proc_U0->num_outputs_empty_n(num_outputs_channel_empty_n);
    Loop_batch_loop_proc_U0->num_outputs_read(Loop_batch_loop_proc_U0_num_outputs_read);
    Loop_batch_loop_proc_U0->num_inputs_dout(num_inputs_channel_dout);
    Loop_batch_loop_proc_U0->num_inputs_empty_n(num_inputs_channel_empty_n);
    Loop_batch_loop_proc_U0->num_inputs_read(Loop_batch_loop_proc_U0_num_inputs_read);
    Loop_batch_loop_proc_U0->p_read(tmp_6_loc_channel_dout);
    Loop_batch_loop_proc_U0->m_axi_mem_AWVALID(Loop_batch_loop_proc_U0_m_axi_mem_AWVALID);
    Loop_batch_loop_proc_U0->m_axi_mem_AWREADY(mem_AWREADY);
    Loop_batch_loop_proc_U0->m_axi_mem_AWADDR(Loop_batch_loop_proc_U0_m_axi_mem_AWADDR);
    Loop_batch_loop_proc_U0->m_axi_mem_AWID(Loop_batch_loop_proc_U0_m_axi_mem_AWID);
    Loop_batch_loop_proc_U0->m_axi_mem_AWLEN(Loop_batch_loop_proc_U0_m_axi_mem_AWLEN);
    Loop_batch_loop_proc_U0->m_axi_mem_AWSIZE(Loop_batch_loop_proc_U0_m_axi_mem_AWSIZE);
    Loop_batch_loop_proc_U0->m_axi_mem_AWBURST(Loop_batch_loop_proc_U0_m_axi_mem_AWBURST);
    Loop_batch_loop_proc_U0->m_axi_mem_AWLOCK(Loop_batch_loop_proc_U0_m_axi_mem_AWLOCK);
    Loop_batch_loop_proc_U0->m_axi_mem_AWCACHE(Loop_batch_loop_proc_U0_m_axi_mem_AWCACHE);
    Loop_batch_loop_proc_U0->m_axi_mem_AWPROT(Loop_batch_loop_proc_U0_m_axi_mem_AWPROT);
    Loop_batch_loop_proc_U0->m_axi_mem_AWQOS(Loop_batch_loop_proc_U0_m_axi_mem_AWQOS);
    Loop_batch_loop_proc_U0->m_axi_mem_AWREGION(Loop_batch_loop_proc_U0_m_axi_mem_AWREGION);
    Loop_batch_loop_proc_U0->m_axi_mem_AWUSER(Loop_batch_loop_proc_U0_m_axi_mem_AWUSER);
    Loop_batch_loop_proc_U0->m_axi_mem_WVALID(Loop_batch_loop_proc_U0_m_axi_mem_WVALID);
    Loop_batch_loop_proc_U0->m_axi_mem_WREADY(mem_WREADY);
    Loop_batch_loop_proc_U0->m_axi_mem_WDATA(Loop_batch_loop_proc_U0_m_axi_mem_WDATA);
    Loop_batch_loop_proc_U0->m_axi_mem_WSTRB(Loop_batch_loop_proc_U0_m_axi_mem_WSTRB);
    Loop_batch_loop_proc_U0->m_axi_mem_WLAST(Loop_batch_loop_proc_U0_m_axi_mem_WLAST);
    Loop_batch_loop_proc_U0->m_axi_mem_WID(Loop_batch_loop_proc_U0_m_axi_mem_WID);
    Loop_batch_loop_proc_U0->m_axi_mem_WUSER(Loop_batch_loop_proc_U0_m_axi_mem_WUSER);
    Loop_batch_loop_proc_U0->m_axi_mem_ARVALID(Loop_batch_loop_proc_U0_m_axi_mem_ARVALID);
    Loop_batch_loop_proc_U0->m_axi_mem_ARREADY(mem_ARREADY);
    Loop_batch_loop_proc_U0->m_axi_mem_ARADDR(Loop_batch_loop_proc_U0_m_axi_mem_ARADDR);
    Loop_batch_loop_proc_U0->m_axi_mem_ARID(Loop_batch_loop_proc_U0_m_axi_mem_ARID);
    Loop_batch_loop_proc_U0->m_axi_mem_ARLEN(Loop_batch_loop_proc_U0_m_axi_mem_ARLEN);
    Loop_batch_loop_proc_U0->m_axi_mem_ARSIZE(Loop_batch_loop_proc_U0_m_axi_mem_ARSIZE);
    Loop_batch_loop_proc_U0->m_axi_mem_ARBURST(Loop_batch_loop_proc_U0_m_axi_mem_ARBURST);
    Loop_batch_loop_proc_U0->m_axi_mem_ARLOCK(Loop_batch_loop_proc_U0_m_axi_mem_ARLOCK);
    Loop_batch_loop_proc_U0->m_axi_mem_ARCACHE(Loop_batch_loop_proc_U0_m_axi_mem_ARCACHE);
    Loop_batch_loop_proc_U0->m_axi_mem_ARPROT(Loop_batch_loop_proc_U0_m_axi_mem_ARPROT);
    Loop_batch_loop_proc_U0->m_axi_mem_ARQOS(Loop_batch_loop_proc_U0_m_axi_mem_ARQOS);
    Loop_batch_loop_proc_U0->m_axi_mem_ARREGION(Loop_batch_loop_proc_U0_m_axi_mem_ARREGION);
    Loop_batch_loop_proc_U0->m_axi_mem_ARUSER(Loop_batch_loop_proc_U0_m_axi_mem_ARUSER);
    Loop_batch_loop_proc_U0->m_axi_mem_RVALID(mem_RVALID);
    Loop_batch_loop_proc_U0->m_axi_mem_RREADY(Loop_batch_loop_proc_U0_m_axi_mem_RREADY);
    Loop_batch_loop_proc_U0->m_axi_mem_RDATA(mem_RDATA);
    Loop_batch_loop_proc_U0->m_axi_mem_RLAST(mem_RLAST);
    Loop_batch_loop_proc_U0->m_axi_mem_RID(mem_RID);
    Loop_batch_loop_proc_U0->m_axi_mem_RUSER(mem_RUSER);
    Loop_batch_loop_proc_U0->m_axi_mem_RRESP(mem_RRESP);
    Loop_batch_loop_proc_U0->m_axi_mem_BVALID(mem_BVALID);
    Loop_batch_loop_proc_U0->m_axi_mem_BREADY(Loop_batch_loop_proc_U0_m_axi_mem_BREADY);
    Loop_batch_loop_proc_U0->m_axi_mem_BRESP(mem_BRESP);
    Loop_batch_loop_proc_U0->m_axi_mem_BID(mem_BID);
    Loop_batch_loop_proc_U0->m_axi_mem_BUSER(mem_BUSER);
    Loop_batch_loop_proc_U0->p_read1(tmp_4_loc_channel_dout);
    Loop_batch_loop_proc_U0->p_read2(tmp_2_loc_channel_dout);
    Loop_batch_loop_proc_U0->p_read3(tmp_1_loc_channel_dout);
    Loop_batch_loop_proc_U0->p_read4(tmp_3_loc_channel_dout);
    num_outputs_channel_U = new fifo_w32_d1_A("num_outputs_channel_U");
    num_outputs_channel_U->clk(ap_clk);
    num_outputs_channel_U->reset(ap_rst_n_inv);
    num_outputs_channel_U->if_read_ce(ap_var_for_const0);
    num_outputs_channel_U->if_write_ce(ap_var_for_const0);
    num_outputs_channel_U->if_din(Block_proc4_U0_num_outputs_out_din);
    num_outputs_channel_U->if_full_n(num_outputs_channel_full_n);
    num_outputs_channel_U->if_write(Block_proc4_U0_num_outputs_out_write);
    num_outputs_channel_U->if_dout(num_outputs_channel_dout);
    num_outputs_channel_U->if_empty_n(num_outputs_channel_empty_n);
    num_outputs_channel_U->if_read(Loop_batch_loop_proc_U0_num_outputs_read);
    num_inputs_channel_U = new fifo_w32_d1_A("num_inputs_channel_U");
    num_inputs_channel_U->clk(ap_clk);
    num_inputs_channel_U->reset(ap_rst_n_inv);
    num_inputs_channel_U->if_read_ce(ap_var_for_const0);
    num_inputs_channel_U->if_write_ce(ap_var_for_const0);
    num_inputs_channel_U->if_din(Block_proc4_U0_num_inputs_out_din);
    num_inputs_channel_U->if_full_n(num_inputs_channel_full_n);
    num_inputs_channel_U->if_write(Block_proc4_U0_num_inputs_out_write);
    num_inputs_channel_U->if_dout(num_inputs_channel_dout);
    num_inputs_channel_U->if_empty_n(num_inputs_channel_empty_n);
    num_inputs_channel_U->if_read(Loop_batch_loop_proc_U0_num_inputs_read);
    batch_size_channel_U = new fifo_w32_d1_A("batch_size_channel_U");
    batch_size_channel_U->clk(ap_clk);
    batch_size_channel_U->reset(ap_rst_n_inv);
    batch_size_channel_U->if_read_ce(ap_var_for_const0);
    batch_size_channel_U->if_write_ce(ap_var_for_const0);
    batch_size_channel_U->if_din(Block_proc4_U0_batch_size_out_din);
    batch_size_channel_U->if_full_n(batch_size_channel_full_n);
    batch_size_channel_U->if_write(Block_proc4_U0_batch_size_out_write);
    batch_size_channel_U->if_dout(batch_size_channel_dout);
    batch_size_channel_U->if_empty_n(batch_size_channel_empty_n);
    batch_size_channel_U->if_read(Loop_batch_loop_proc_U0_batch_size_read);
    tmp_2_loc_channel_U = new fifo_w64_d2_A("tmp_2_loc_channel_U");
    tmp_2_loc_channel_U->clk(ap_clk);
    tmp_2_loc_channel_U->reset(ap_rst_n_inv);
    tmp_2_loc_channel_U->if_read_ce(ap_var_for_const0);
    tmp_2_loc_channel_U->if_write_ce(ap_var_for_const0);
    tmp_2_loc_channel_U->if_din(Block_proc4_U0_ap_return_0);
    tmp_2_loc_channel_U->if_full_n(tmp_2_loc_channel_full_n);
    tmp_2_loc_channel_U->if_write(ap_channel_done_tmp_2_loc_channel);
    tmp_2_loc_channel_U->if_dout(tmp_2_loc_channel_dout);
    tmp_2_loc_channel_U->if_empty_n(tmp_2_loc_channel_empty_n);
    tmp_2_loc_channel_U->if_read(Loop_batch_loop_proc_U0_ap_ready);
    tmp_1_loc_channel_U = new fifo_w64_d2_A("tmp_1_loc_channel_U");
    tmp_1_loc_channel_U->clk(ap_clk);
    tmp_1_loc_channel_U->reset(ap_rst_n_inv);
    tmp_1_loc_channel_U->if_read_ce(ap_var_for_const0);
    tmp_1_loc_channel_U->if_write_ce(ap_var_for_const0);
    tmp_1_loc_channel_U->if_din(Block_proc4_U0_ap_return_1);
    tmp_1_loc_channel_U->if_full_n(tmp_1_loc_channel_full_n);
    tmp_1_loc_channel_U->if_write(ap_channel_done_tmp_1_loc_channel);
    tmp_1_loc_channel_U->if_dout(tmp_1_loc_channel_dout);
    tmp_1_loc_channel_U->if_empty_n(tmp_1_loc_channel_empty_n);
    tmp_1_loc_channel_U->if_read(Loop_batch_loop_proc_U0_ap_ready);
    tmp_3_loc_channel_U = new fifo_w64_d2_A("tmp_3_loc_channel_U");
    tmp_3_loc_channel_U->clk(ap_clk);
    tmp_3_loc_channel_U->reset(ap_rst_n_inv);
    tmp_3_loc_channel_U->if_read_ce(ap_var_for_const0);
    tmp_3_loc_channel_U->if_write_ce(ap_var_for_const0);
    tmp_3_loc_channel_U->if_din(Block_proc4_U0_ap_return_2);
    tmp_3_loc_channel_U->if_full_n(tmp_3_loc_channel_full_n);
    tmp_3_loc_channel_U->if_write(ap_channel_done_tmp_3_loc_channel);
    tmp_3_loc_channel_U->if_dout(tmp_3_loc_channel_dout);
    tmp_3_loc_channel_U->if_empty_n(tmp_3_loc_channel_empty_n);
    tmp_3_loc_channel_U->if_read(Loop_batch_loop_proc_U0_ap_ready);
    tmp_4_loc_channel_U = new fifo_w1_d2_A("tmp_4_loc_channel_U");
    tmp_4_loc_channel_U->clk(ap_clk);
    tmp_4_loc_channel_U->reset(ap_rst_n_inv);
    tmp_4_loc_channel_U->if_read_ce(ap_var_for_const0);
    tmp_4_loc_channel_U->if_write_ce(ap_var_for_const0);
    tmp_4_loc_channel_U->if_din(Block_proc4_U0_ap_return_3);
    tmp_4_loc_channel_U->if_full_n(tmp_4_loc_channel_full_n);
    tmp_4_loc_channel_U->if_write(ap_channel_done_tmp_4_loc_channel);
    tmp_4_loc_channel_U->if_dout(tmp_4_loc_channel_dout);
    tmp_4_loc_channel_U->if_empty_n(tmp_4_loc_channel_empty_n);
    tmp_4_loc_channel_U->if_read(Loop_batch_loop_proc_U0_ap_ready);
    tmp_6_loc_channel_U = new fifo_w64_d2_A("tmp_6_loc_channel_U");
    tmp_6_loc_channel_U->clk(ap_clk);
    tmp_6_loc_channel_U->reset(ap_rst_n_inv);
    tmp_6_loc_channel_U->if_read_ce(ap_var_for_const0);
    tmp_6_loc_channel_U->if_write_ce(ap_var_for_const0);
    tmp_6_loc_channel_U->if_din(Block_proc4_U0_ap_return_4);
    tmp_6_loc_channel_U->if_full_n(tmp_6_loc_channel_full_n);
    tmp_6_loc_channel_U->if_write(ap_channel_done_tmp_6_loc_channel);
    tmp_6_loc_channel_U->if_dout(tmp_6_loc_channel_dout);
    tmp_6_loc_channel_U->if_empty_n(tmp_6_loc_channel_empty_n);
    tmp_6_loc_channel_U->if_read(Loop_batch_loop_proc_U0_ap_ready);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Block_proc4_U0_ap_continue);
    sensitive << ( ap_sync_channel_write_tmp_6_loc_channel );
    sensitive << ( ap_sync_channel_write_tmp_4_loc_channel );
    sensitive << ( ap_sync_channel_write_tmp_3_loc_channel );
    sensitive << ( ap_sync_channel_write_tmp_1_loc_channel );
    sensitive << ( ap_sync_channel_write_tmp_2_loc_channel );

    SC_METHOD(thread_Block_proc4_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_Block_proc4_U0_ap_ready );

    SC_METHOD(thread_Block_proc4_U0_start_full_n);

    SC_METHOD(thread_Block_proc4_U0_start_write);

    SC_METHOD(thread_Loop_batch_loop_proc_U0_ap_continue);

    SC_METHOD(thread_Loop_batch_loop_proc_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( tmp_2_loc_channel_empty_n );
    sensitive << ( tmp_1_loc_channel_empty_n );
    sensitive << ( tmp_3_loc_channel_empty_n );
    sensitive << ( tmp_4_loc_channel_empty_n );
    sensitive << ( tmp_6_loc_channel_empty_n );
    sensitive << ( ap_sync_reg_Loop_batch_loop_proc_U0_ap_ready );

    SC_METHOD(thread_Loop_batch_loop_proc_U0_start_full_n);

    SC_METHOD(thread_Loop_batch_loop_proc_U0_start_write);

    SC_METHOD(thread_ap_channel_done_tmp_1_loc_channel);
    sensitive << ( Block_proc4_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_1_loc_channel );

    SC_METHOD(thread_ap_channel_done_tmp_2_loc_channel);
    sensitive << ( Block_proc4_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_2_loc_channel );

    SC_METHOD(thread_ap_channel_done_tmp_3_loc_channel);
    sensitive << ( Block_proc4_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_3_loc_channel );

    SC_METHOD(thread_ap_channel_done_tmp_4_loc_channel);
    sensitive << ( Block_proc4_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_4_loc_channel );

    SC_METHOD(thread_ap_channel_done_tmp_6_loc_channel);
    sensitive << ( Block_proc4_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_6_loc_channel );

    SC_METHOD(thread_ap_done);
    sensitive << ( Loop_batch_loop_proc_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( Block_proc4_U0_ap_idle );
    sensitive << ( Loop_batch_loop_proc_U0_ap_idle );
    sensitive << ( tmp_2_loc_channel_empty_n );
    sensitive << ( tmp_1_loc_channel_empty_n );
    sensitive << ( tmp_3_loc_channel_empty_n );
    sensitive << ( tmp_4_loc_channel_empty_n );
    sensitive << ( tmp_6_loc_channel_empty_n );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sync_ready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_Block_proc4_U0_ap_ready);
    sensitive << ( Block_proc4_U0_ap_ready );
    sensitive << ( ap_sync_reg_Block_proc4_U0_ap_ready );

    SC_METHOD(thread_ap_sync_Loop_batch_loop_proc_U0_ap_ready);
    sensitive << ( Loop_batch_loop_proc_U0_ap_ready );
    sensitive << ( ap_sync_reg_Loop_batch_loop_proc_U0_ap_ready );

    SC_METHOD(thread_ap_sync_channel_write_tmp_1_loc_channel);
    sensitive << ( ap_channel_done_tmp_1_loc_channel );
    sensitive << ( tmp_1_loc_channel_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_1_loc_channel );

    SC_METHOD(thread_ap_sync_channel_write_tmp_2_loc_channel);
    sensitive << ( ap_channel_done_tmp_2_loc_channel );
    sensitive << ( tmp_2_loc_channel_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_2_loc_channel );

    SC_METHOD(thread_ap_sync_channel_write_tmp_3_loc_channel);
    sensitive << ( ap_channel_done_tmp_3_loc_channel );
    sensitive << ( tmp_3_loc_channel_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_3_loc_channel );

    SC_METHOD(thread_ap_sync_channel_write_tmp_4_loc_channel);
    sensitive << ( ap_channel_done_tmp_4_loc_channel );
    sensitive << ( tmp_4_loc_channel_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_4_loc_channel );

    SC_METHOD(thread_ap_sync_channel_write_tmp_6_loc_channel);
    sensitive << ( ap_channel_done_tmp_6_loc_channel );
    sensitive << ( tmp_6_loc_channel_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_6_loc_channel );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( Loop_batch_loop_proc_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( ap_sync_Loop_batch_loop_proc_U0_ap_ready );
    sensitive << ( ap_sync_Block_proc4_U0_ap_ready );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_sync_reg_channel_write_tmp_6_loc_channel = SC_LOGIC_0;
    ap_sync_reg_channel_write_tmp_4_loc_channel = SC_LOGIC_0;
    ap_sync_reg_channel_write_tmp_3_loc_channel = SC_LOGIC_0;
    ap_sync_reg_channel_write_tmp_1_loc_channel = SC_LOGIC_0;
    ap_sync_reg_channel_write_tmp_2_loc_channel = SC_LOGIC_0;
    ap_sync_reg_Loop_batch_loop_proc_U0_ap_ready = SC_LOGIC_0;
    Loop_batch_loop_proc_U0_ap_ready_count = "00";
    ap_sync_reg_Block_proc4_U0_ap_ready = SC_LOGIC_0;
    Block_proc4_U0_ap_ready_count = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fc_layer_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, s_axi_CTRL_BUS_AWVALID, "(port)s_axi_CTRL_BUS_AWVALID");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_AWREADY, "(port)s_axi_CTRL_BUS_AWREADY");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_AWADDR, "(port)s_axi_CTRL_BUS_AWADDR");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_WVALID, "(port)s_axi_CTRL_BUS_WVALID");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_WREADY, "(port)s_axi_CTRL_BUS_WREADY");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_WDATA, "(port)s_axi_CTRL_BUS_WDATA");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_WSTRB, "(port)s_axi_CTRL_BUS_WSTRB");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_ARVALID, "(port)s_axi_CTRL_BUS_ARVALID");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_ARREADY, "(port)s_axi_CTRL_BUS_ARREADY");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_ARADDR, "(port)s_axi_CTRL_BUS_ARADDR");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_RVALID, "(port)s_axi_CTRL_BUS_RVALID");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_RREADY, "(port)s_axi_CTRL_BUS_RREADY");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_RDATA, "(port)s_axi_CTRL_BUS_RDATA");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_RRESP, "(port)s_axi_CTRL_BUS_RRESP");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_BVALID, "(port)s_axi_CTRL_BUS_BVALID");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_BREADY, "(port)s_axi_CTRL_BUS_BREADY");
    sc_trace(mVcdFile, s_axi_CTRL_BUS_BRESP, "(port)s_axi_CTRL_BUS_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
    sc_trace(mVcdFile, m_axi_mem_AWVALID, "(port)m_axi_mem_AWVALID");
    sc_trace(mVcdFile, m_axi_mem_AWREADY, "(port)m_axi_mem_AWREADY");
    sc_trace(mVcdFile, m_axi_mem_AWADDR, "(port)m_axi_mem_AWADDR");
    sc_trace(mVcdFile, m_axi_mem_AWID, "(port)m_axi_mem_AWID");
    sc_trace(mVcdFile, m_axi_mem_AWLEN, "(port)m_axi_mem_AWLEN");
    sc_trace(mVcdFile, m_axi_mem_AWSIZE, "(port)m_axi_mem_AWSIZE");
    sc_trace(mVcdFile, m_axi_mem_AWBURST, "(port)m_axi_mem_AWBURST");
    sc_trace(mVcdFile, m_axi_mem_AWLOCK, "(port)m_axi_mem_AWLOCK");
    sc_trace(mVcdFile, m_axi_mem_AWCACHE, "(port)m_axi_mem_AWCACHE");
    sc_trace(mVcdFile, m_axi_mem_AWPROT, "(port)m_axi_mem_AWPROT");
    sc_trace(mVcdFile, m_axi_mem_AWQOS, "(port)m_axi_mem_AWQOS");
    sc_trace(mVcdFile, m_axi_mem_AWREGION, "(port)m_axi_mem_AWREGION");
    sc_trace(mVcdFile, m_axi_mem_AWUSER, "(port)m_axi_mem_AWUSER");
    sc_trace(mVcdFile, m_axi_mem_WVALID, "(port)m_axi_mem_WVALID");
    sc_trace(mVcdFile, m_axi_mem_WREADY, "(port)m_axi_mem_WREADY");
    sc_trace(mVcdFile, m_axi_mem_WDATA, "(port)m_axi_mem_WDATA");
    sc_trace(mVcdFile, m_axi_mem_WSTRB, "(port)m_axi_mem_WSTRB");
    sc_trace(mVcdFile, m_axi_mem_WLAST, "(port)m_axi_mem_WLAST");
    sc_trace(mVcdFile, m_axi_mem_WID, "(port)m_axi_mem_WID");
    sc_trace(mVcdFile, m_axi_mem_WUSER, "(port)m_axi_mem_WUSER");
    sc_trace(mVcdFile, m_axi_mem_ARVALID, "(port)m_axi_mem_ARVALID");
    sc_trace(mVcdFile, m_axi_mem_ARREADY, "(port)m_axi_mem_ARREADY");
    sc_trace(mVcdFile, m_axi_mem_ARADDR, "(port)m_axi_mem_ARADDR");
    sc_trace(mVcdFile, m_axi_mem_ARID, "(port)m_axi_mem_ARID");
    sc_trace(mVcdFile, m_axi_mem_ARLEN, "(port)m_axi_mem_ARLEN");
    sc_trace(mVcdFile, m_axi_mem_ARSIZE, "(port)m_axi_mem_ARSIZE");
    sc_trace(mVcdFile, m_axi_mem_ARBURST, "(port)m_axi_mem_ARBURST");
    sc_trace(mVcdFile, m_axi_mem_ARLOCK, "(port)m_axi_mem_ARLOCK");
    sc_trace(mVcdFile, m_axi_mem_ARCACHE, "(port)m_axi_mem_ARCACHE");
    sc_trace(mVcdFile, m_axi_mem_ARPROT, "(port)m_axi_mem_ARPROT");
    sc_trace(mVcdFile, m_axi_mem_ARQOS, "(port)m_axi_mem_ARQOS");
    sc_trace(mVcdFile, m_axi_mem_ARREGION, "(port)m_axi_mem_ARREGION");
    sc_trace(mVcdFile, m_axi_mem_ARUSER, "(port)m_axi_mem_ARUSER");
    sc_trace(mVcdFile, m_axi_mem_RVALID, "(port)m_axi_mem_RVALID");
    sc_trace(mVcdFile, m_axi_mem_RREADY, "(port)m_axi_mem_RREADY");
    sc_trace(mVcdFile, m_axi_mem_RDATA, "(port)m_axi_mem_RDATA");
    sc_trace(mVcdFile, m_axi_mem_RLAST, "(port)m_axi_mem_RLAST");
    sc_trace(mVcdFile, m_axi_mem_RID, "(port)m_axi_mem_RID");
    sc_trace(mVcdFile, m_axi_mem_RUSER, "(port)m_axi_mem_RUSER");
    sc_trace(mVcdFile, m_axi_mem_RRESP, "(port)m_axi_mem_RRESP");
    sc_trace(mVcdFile, m_axi_mem_BVALID, "(port)m_axi_mem_BVALID");
    sc_trace(mVcdFile, m_axi_mem_BREADY, "(port)m_axi_mem_BREADY");
    sc_trace(mVcdFile, m_axi_mem_BRESP, "(port)m_axi_mem_BRESP");
    sc_trace(mVcdFile, m_axi_mem_BID, "(port)m_axi_mem_BID");
    sc_trace(mVcdFile, m_axi_mem_BUSER, "(port)m_axi_mem_BUSER");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, input_offset, "input_offset");
    sc_trace(mVcdFile, output_offset, "output_offset");
    sc_trace(mVcdFile, batch_size, "batch_size");
    sc_trace(mVcdFile, num_inputs, "num_inputs");
    sc_trace(mVcdFile, num_outputs, "num_outputs");
    sc_trace(mVcdFile, enable_relu, "enable_relu");
    sc_trace(mVcdFile, mem_AWREADY, "mem_AWREADY");
    sc_trace(mVcdFile, mem_WREADY, "mem_WREADY");
    sc_trace(mVcdFile, mem_ARREADY, "mem_ARREADY");
    sc_trace(mVcdFile, mem_RVALID, "mem_RVALID");
    sc_trace(mVcdFile, mem_RDATA, "mem_RDATA");
    sc_trace(mVcdFile, mem_RLAST, "mem_RLAST");
    sc_trace(mVcdFile, mem_RID, "mem_RID");
    sc_trace(mVcdFile, mem_RUSER, "mem_RUSER");
    sc_trace(mVcdFile, mem_RRESP, "mem_RRESP");
    sc_trace(mVcdFile, mem_BVALID, "mem_BVALID");
    sc_trace(mVcdFile, mem_BRESP, "mem_BRESP");
    sc_trace(mVcdFile, mem_BID, "mem_BID");
    sc_trace(mVcdFile, mem_BUSER, "mem_BUSER");
    sc_trace(mVcdFile, Block_proc4_U0_ap_start, "Block_proc4_U0_ap_start");
    sc_trace(mVcdFile, Block_proc4_U0_ap_done, "Block_proc4_U0_ap_done");
    sc_trace(mVcdFile, Block_proc4_U0_ap_continue, "Block_proc4_U0_ap_continue");
    sc_trace(mVcdFile, Block_proc4_U0_ap_idle, "Block_proc4_U0_ap_idle");
    sc_trace(mVcdFile, Block_proc4_U0_ap_ready, "Block_proc4_U0_ap_ready");
    sc_trace(mVcdFile, Block_proc4_U0_num_outputs_out_din, "Block_proc4_U0_num_outputs_out_din");
    sc_trace(mVcdFile, Block_proc4_U0_num_outputs_out_write, "Block_proc4_U0_num_outputs_out_write");
    sc_trace(mVcdFile, Block_proc4_U0_num_inputs_out_din, "Block_proc4_U0_num_inputs_out_din");
    sc_trace(mVcdFile, Block_proc4_U0_num_inputs_out_write, "Block_proc4_U0_num_inputs_out_write");
    sc_trace(mVcdFile, Block_proc4_U0_batch_size_out_din, "Block_proc4_U0_batch_size_out_din");
    sc_trace(mVcdFile, Block_proc4_U0_batch_size_out_write, "Block_proc4_U0_batch_size_out_write");
    sc_trace(mVcdFile, Block_proc4_U0_ap_return_0, "Block_proc4_U0_ap_return_0");
    sc_trace(mVcdFile, Block_proc4_U0_ap_return_1, "Block_proc4_U0_ap_return_1");
    sc_trace(mVcdFile, Block_proc4_U0_ap_return_2, "Block_proc4_U0_ap_return_2");
    sc_trace(mVcdFile, Block_proc4_U0_ap_return_3, "Block_proc4_U0_ap_return_3");
    sc_trace(mVcdFile, Block_proc4_U0_ap_return_4, "Block_proc4_U0_ap_return_4");
    sc_trace(mVcdFile, ap_channel_done_tmp_6_loc_channel, "ap_channel_done_tmp_6_loc_channel");
    sc_trace(mVcdFile, tmp_6_loc_channel_full_n, "tmp_6_loc_channel_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_6_loc_channel, "ap_sync_reg_channel_write_tmp_6_loc_channel");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_6_loc_channel, "ap_sync_channel_write_tmp_6_loc_channel");
    sc_trace(mVcdFile, ap_channel_done_tmp_4_loc_channel, "ap_channel_done_tmp_4_loc_channel");
    sc_trace(mVcdFile, tmp_4_loc_channel_full_n, "tmp_4_loc_channel_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_4_loc_channel, "ap_sync_reg_channel_write_tmp_4_loc_channel");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_4_loc_channel, "ap_sync_channel_write_tmp_4_loc_channel");
    sc_trace(mVcdFile, ap_channel_done_tmp_3_loc_channel, "ap_channel_done_tmp_3_loc_channel");
    sc_trace(mVcdFile, tmp_3_loc_channel_full_n, "tmp_3_loc_channel_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_3_loc_channel, "ap_sync_reg_channel_write_tmp_3_loc_channel");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_3_loc_channel, "ap_sync_channel_write_tmp_3_loc_channel");
    sc_trace(mVcdFile, ap_channel_done_tmp_1_loc_channel, "ap_channel_done_tmp_1_loc_channel");
    sc_trace(mVcdFile, tmp_1_loc_channel_full_n, "tmp_1_loc_channel_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_1_loc_channel, "ap_sync_reg_channel_write_tmp_1_loc_channel");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_1_loc_channel, "ap_sync_channel_write_tmp_1_loc_channel");
    sc_trace(mVcdFile, ap_channel_done_tmp_2_loc_channel, "ap_channel_done_tmp_2_loc_channel");
    sc_trace(mVcdFile, tmp_2_loc_channel_full_n, "tmp_2_loc_channel_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_2_loc_channel, "ap_sync_reg_channel_write_tmp_2_loc_channel");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_2_loc_channel, "ap_sync_channel_write_tmp_2_loc_channel");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_ap_start, "Loop_batch_loop_proc_U0_ap_start");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_ap_done, "Loop_batch_loop_proc_U0_ap_done");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_ap_continue, "Loop_batch_loop_proc_U0_ap_continue");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_ap_idle, "Loop_batch_loop_proc_U0_ap_idle");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_ap_ready, "Loop_batch_loop_proc_U0_ap_ready");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_batch_size_read, "Loop_batch_loop_proc_U0_batch_size_read");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_num_outputs_read, "Loop_batch_loop_proc_U0_num_outputs_read");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_num_inputs_read, "Loop_batch_loop_proc_U0_num_inputs_read");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_AWVALID, "Loop_batch_loop_proc_U0_m_axi_mem_AWVALID");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_AWADDR, "Loop_batch_loop_proc_U0_m_axi_mem_AWADDR");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_AWID, "Loop_batch_loop_proc_U0_m_axi_mem_AWID");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_AWLEN, "Loop_batch_loop_proc_U0_m_axi_mem_AWLEN");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_AWSIZE, "Loop_batch_loop_proc_U0_m_axi_mem_AWSIZE");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_AWBURST, "Loop_batch_loop_proc_U0_m_axi_mem_AWBURST");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_AWLOCK, "Loop_batch_loop_proc_U0_m_axi_mem_AWLOCK");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_AWCACHE, "Loop_batch_loop_proc_U0_m_axi_mem_AWCACHE");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_AWPROT, "Loop_batch_loop_proc_U0_m_axi_mem_AWPROT");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_AWQOS, "Loop_batch_loop_proc_U0_m_axi_mem_AWQOS");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_AWREGION, "Loop_batch_loop_proc_U0_m_axi_mem_AWREGION");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_AWUSER, "Loop_batch_loop_proc_U0_m_axi_mem_AWUSER");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_WVALID, "Loop_batch_loop_proc_U0_m_axi_mem_WVALID");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_WDATA, "Loop_batch_loop_proc_U0_m_axi_mem_WDATA");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_WSTRB, "Loop_batch_loop_proc_U0_m_axi_mem_WSTRB");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_WLAST, "Loop_batch_loop_proc_U0_m_axi_mem_WLAST");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_WID, "Loop_batch_loop_proc_U0_m_axi_mem_WID");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_WUSER, "Loop_batch_loop_proc_U0_m_axi_mem_WUSER");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_ARVALID, "Loop_batch_loop_proc_U0_m_axi_mem_ARVALID");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_ARADDR, "Loop_batch_loop_proc_U0_m_axi_mem_ARADDR");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_ARID, "Loop_batch_loop_proc_U0_m_axi_mem_ARID");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_ARLEN, "Loop_batch_loop_proc_U0_m_axi_mem_ARLEN");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_ARSIZE, "Loop_batch_loop_proc_U0_m_axi_mem_ARSIZE");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_ARBURST, "Loop_batch_loop_proc_U0_m_axi_mem_ARBURST");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_ARLOCK, "Loop_batch_loop_proc_U0_m_axi_mem_ARLOCK");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_ARCACHE, "Loop_batch_loop_proc_U0_m_axi_mem_ARCACHE");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_ARPROT, "Loop_batch_loop_proc_U0_m_axi_mem_ARPROT");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_ARQOS, "Loop_batch_loop_proc_U0_m_axi_mem_ARQOS");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_ARREGION, "Loop_batch_loop_proc_U0_m_axi_mem_ARREGION");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_ARUSER, "Loop_batch_loop_proc_U0_m_axi_mem_ARUSER");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_RREADY, "Loop_batch_loop_proc_U0_m_axi_mem_RREADY");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_m_axi_mem_BREADY, "Loop_batch_loop_proc_U0_m_axi_mem_BREADY");
    sc_trace(mVcdFile, num_outputs_channel_full_n, "num_outputs_channel_full_n");
    sc_trace(mVcdFile, num_outputs_channel_dout, "num_outputs_channel_dout");
    sc_trace(mVcdFile, num_outputs_channel_empty_n, "num_outputs_channel_empty_n");
    sc_trace(mVcdFile, num_inputs_channel_full_n, "num_inputs_channel_full_n");
    sc_trace(mVcdFile, num_inputs_channel_dout, "num_inputs_channel_dout");
    sc_trace(mVcdFile, num_inputs_channel_empty_n, "num_inputs_channel_empty_n");
    sc_trace(mVcdFile, batch_size_channel_full_n, "batch_size_channel_full_n");
    sc_trace(mVcdFile, batch_size_channel_dout, "batch_size_channel_dout");
    sc_trace(mVcdFile, batch_size_channel_empty_n, "batch_size_channel_empty_n");
    sc_trace(mVcdFile, tmp_2_loc_channel_dout, "tmp_2_loc_channel_dout");
    sc_trace(mVcdFile, tmp_2_loc_channel_empty_n, "tmp_2_loc_channel_empty_n");
    sc_trace(mVcdFile, tmp_1_loc_channel_dout, "tmp_1_loc_channel_dout");
    sc_trace(mVcdFile, tmp_1_loc_channel_empty_n, "tmp_1_loc_channel_empty_n");
    sc_trace(mVcdFile, tmp_3_loc_channel_dout, "tmp_3_loc_channel_dout");
    sc_trace(mVcdFile, tmp_3_loc_channel_empty_n, "tmp_3_loc_channel_empty_n");
    sc_trace(mVcdFile, tmp_4_loc_channel_dout, "tmp_4_loc_channel_dout");
    sc_trace(mVcdFile, tmp_4_loc_channel_empty_n, "tmp_4_loc_channel_empty_n");
    sc_trace(mVcdFile, tmp_6_loc_channel_dout, "tmp_6_loc_channel_dout");
    sc_trace(mVcdFile, tmp_6_loc_channel_empty_n, "tmp_6_loc_channel_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, ap_sync_reg_Loop_batch_loop_proc_U0_ap_ready, "ap_sync_reg_Loop_batch_loop_proc_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_Loop_batch_loop_proc_U0_ap_ready, "ap_sync_Loop_batch_loop_proc_U0_ap_ready");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_ap_ready_count, "Loop_batch_loop_proc_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_Block_proc4_U0_ap_ready, "ap_sync_reg_Block_proc4_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_Block_proc4_U0_ap_ready, "ap_sync_Block_proc4_U0_ap_ready");
    sc_trace(mVcdFile, Block_proc4_U0_ap_ready_count, "Block_proc4_U0_ap_ready_count");
    sc_trace(mVcdFile, Block_proc4_U0_start_full_n, "Block_proc4_U0_start_full_n");
    sc_trace(mVcdFile, Block_proc4_U0_start_write, "Block_proc4_U0_start_write");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_start_full_n, "Loop_batch_loop_proc_U0_start_full_n");
    sc_trace(mVcdFile, Loop_batch_loop_proc_U0_start_write, "Loop_batch_loop_proc_U0_start_write");
#endif

    }
    mHdltvinHandle.open("fc_layer.hdltvin.dat");
    mHdltvoutHandle.open("fc_layer.hdltvout.dat");
}

fc_layer::~fc_layer() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete fc_layer_CTRL_BUS_s_axi_U;
    delete fc_layer_mem_m_axi_U;
    delete Block_proc4_U0;
    delete Loop_batch_loop_proc_U0;
    delete num_outputs_channel_U;
    delete num_inputs_channel_U;
    delete batch_size_channel_U;
    delete tmp_2_loc_channel_U;
    delete tmp_1_loc_channel_U;
    delete tmp_3_loc_channel_U;
    delete tmp_4_loc_channel_U;
    delete tmp_6_loc_channel_U;
}

void fc_layer::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void fc_layer::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(Block_proc4_U0_ap_ready.read(), ap_const_logic_0))) {
        Block_proc4_U0_ap_ready_count = (!Block_proc4_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_proc4_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_ready.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, Block_proc4_U0_ap_ready.read()))) {
        Block_proc4_U0_ap_ready_count = (!Block_proc4_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_proc4_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_0, Loop_batch_loop_proc_U0_ap_ready.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()))) {
        Loop_batch_loop_proc_U0_ap_ready_count = (!Loop_batch_loop_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Loop_batch_loop_proc_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, Loop_batch_loop_proc_U0_ap_ready.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_ready.read()))) {
        Loop_batch_loop_proc_U0_ap_ready_count = (!Loop_batch_loop_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Loop_batch_loop_proc_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_Block_proc4_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_Block_proc4_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_Block_proc4_U0_ap_ready = ap_sync_Block_proc4_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_Loop_batch_loop_proc_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_Loop_batch_loop_proc_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_Loop_batch_loop_proc_U0_ap_ready = ap_sync_Loop_batch_loop_proc_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_1_loc_channel = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_proc4_U0_ap_done.read() & 
             Block_proc4_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_1_loc_channel = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_1_loc_channel = ap_sync_channel_write_tmp_1_loc_channel.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_2_loc_channel = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_proc4_U0_ap_done.read() & 
             Block_proc4_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_2_loc_channel = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_2_loc_channel = ap_sync_channel_write_tmp_2_loc_channel.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_3_loc_channel = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_proc4_U0_ap_done.read() & 
             Block_proc4_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_3_loc_channel = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_3_loc_channel = ap_sync_channel_write_tmp_3_loc_channel.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_4_loc_channel = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_proc4_U0_ap_done.read() & 
             Block_proc4_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_4_loc_channel = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_4_loc_channel = ap_sync_channel_write_tmp_4_loc_channel.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_6_loc_channel = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_proc4_U0_ap_done.read() & 
             Block_proc4_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_6_loc_channel = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_6_loc_channel = ap_sync_channel_write_tmp_6_loc_channel.read();
        }
    }
}

void fc_layer::thread_Block_proc4_U0_ap_continue() {
    Block_proc4_U0_ap_continue = (ap_sync_channel_write_tmp_6_loc_channel.read() & ap_sync_channel_write_tmp_4_loc_channel.read() & ap_sync_channel_write_tmp_3_loc_channel.read() & ap_sync_channel_write_tmp_1_loc_channel.read() & ap_sync_channel_write_tmp_2_loc_channel.read());
}

void fc_layer::thread_Block_proc4_U0_ap_start() {
    Block_proc4_U0_ap_start = (ap_start.read() & (ap_sync_reg_Block_proc4_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void fc_layer::thread_Block_proc4_U0_start_full_n() {
    Block_proc4_U0_start_full_n = ap_const_logic_0;
}

void fc_layer::thread_Block_proc4_U0_start_write() {
    Block_proc4_U0_start_write = ap_const_logic_0;
}

void fc_layer::thread_Loop_batch_loop_proc_U0_ap_continue() {
    Loop_batch_loop_proc_U0_ap_continue = ap_const_logic_1;
}

void fc_layer::thread_Loop_batch_loop_proc_U0_ap_start() {
    Loop_batch_loop_proc_U0_ap_start = (ap_start.read() & tmp_2_loc_channel_empty_n.read() & tmp_1_loc_channel_empty_n.read() & tmp_3_loc_channel_empty_n.read() & tmp_4_loc_channel_empty_n.read() & tmp_6_loc_channel_empty_n.read() & (ap_sync_reg_Loop_batch_loop_proc_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void fc_layer::thread_Loop_batch_loop_proc_U0_start_full_n() {
    Loop_batch_loop_proc_U0_start_full_n = ap_const_logic_0;
}

void fc_layer::thread_Loop_batch_loop_proc_U0_start_write() {
    Loop_batch_loop_proc_U0_start_write = ap_const_logic_0;
}

void fc_layer::thread_ap_channel_done_tmp_1_loc_channel() {
    ap_channel_done_tmp_1_loc_channel = (Block_proc4_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_1_loc_channel.read() ^ 
  ap_const_logic_1));
}

void fc_layer::thread_ap_channel_done_tmp_2_loc_channel() {
    ap_channel_done_tmp_2_loc_channel = (Block_proc4_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_2_loc_channel.read() ^ 
  ap_const_logic_1));
}

void fc_layer::thread_ap_channel_done_tmp_3_loc_channel() {
    ap_channel_done_tmp_3_loc_channel = (Block_proc4_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_3_loc_channel.read() ^ 
  ap_const_logic_1));
}

void fc_layer::thread_ap_channel_done_tmp_4_loc_channel() {
    ap_channel_done_tmp_4_loc_channel = (Block_proc4_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_4_loc_channel.read() ^ 
  ap_const_logic_1));
}

void fc_layer::thread_ap_channel_done_tmp_6_loc_channel() {
    ap_channel_done_tmp_6_loc_channel = (Block_proc4_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_6_loc_channel.read() ^ 
  ap_const_logic_1));
}

void fc_layer::thread_ap_done() {
    ap_done = Loop_batch_loop_proc_U0_ap_done.read();
}

void fc_layer::thread_ap_idle() {
    ap_idle = (Block_proc4_U0_ap_idle.read() & Loop_batch_loop_proc_U0_ap_idle.read() & (tmp_2_loc_channel_empty_n.read() ^ 
  ap_const_logic_1) & (tmp_1_loc_channel_empty_n.read() ^ 
  ap_const_logic_1) & (tmp_3_loc_channel_empty_n.read() ^ 
  ap_const_logic_1) & (tmp_4_loc_channel_empty_n.read() ^ 
  ap_const_logic_1) & (tmp_6_loc_channel_empty_n.read() ^ 
  ap_const_logic_1));
}

void fc_layer::thread_ap_ready() {
    ap_ready = ap_sync_ready.read();
}

void fc_layer::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void fc_layer::thread_ap_sync_Block_proc4_U0_ap_ready() {
    ap_sync_Block_proc4_U0_ap_ready = (Block_proc4_U0_ap_ready.read() | ap_sync_reg_Block_proc4_U0_ap_ready.read());
}

void fc_layer::thread_ap_sync_Loop_batch_loop_proc_U0_ap_ready() {
    ap_sync_Loop_batch_loop_proc_U0_ap_ready = (Loop_batch_loop_proc_U0_ap_ready.read() | ap_sync_reg_Loop_batch_loop_proc_U0_ap_ready.read());
}

void fc_layer::thread_ap_sync_channel_write_tmp_1_loc_channel() {
    ap_sync_channel_write_tmp_1_loc_channel = ((ap_channel_done_tmp_1_loc_channel.read() & 
  tmp_1_loc_channel_full_n.read()) | ap_sync_reg_channel_write_tmp_1_loc_channel.read());
}

void fc_layer::thread_ap_sync_channel_write_tmp_2_loc_channel() {
    ap_sync_channel_write_tmp_2_loc_channel = ((ap_channel_done_tmp_2_loc_channel.read() & 
  tmp_2_loc_channel_full_n.read()) | ap_sync_reg_channel_write_tmp_2_loc_channel.read());
}

void fc_layer::thread_ap_sync_channel_write_tmp_3_loc_channel() {
    ap_sync_channel_write_tmp_3_loc_channel = ((ap_channel_done_tmp_3_loc_channel.read() & 
  tmp_3_loc_channel_full_n.read()) | ap_sync_reg_channel_write_tmp_3_loc_channel.read());
}

void fc_layer::thread_ap_sync_channel_write_tmp_4_loc_channel() {
    ap_sync_channel_write_tmp_4_loc_channel = ((ap_channel_done_tmp_4_loc_channel.read() & 
  tmp_4_loc_channel_full_n.read()) | ap_sync_reg_channel_write_tmp_4_loc_channel.read());
}

void fc_layer::thread_ap_sync_channel_write_tmp_6_loc_channel() {
    ap_sync_channel_write_tmp_6_loc_channel = ((ap_channel_done_tmp_6_loc_channel.read() & 
  tmp_6_loc_channel_full_n.read()) | ap_sync_reg_channel_write_tmp_6_loc_channel.read());
}

void fc_layer::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_1;
}

void fc_layer::thread_ap_sync_done() {
    ap_sync_done = Loop_batch_loop_proc_U0_ap_done.read();
}

void fc_layer::thread_ap_sync_ready() {
    ap_sync_ready = (ap_sync_Loop_batch_loop_proc_U0_ap_ready.read() & ap_sync_Block_proc4_U0_ap_ready.read());
}

void fc_layer::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"s_axi_CTRL_BUS_AWVALID\" :  \"" << s_axi_CTRL_BUS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_CTRL_BUS_AWREADY\" :  \"" << s_axi_CTRL_BUS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_BUS_AWADDR\" :  \"" << s_axi_CTRL_BUS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_BUS_WVALID\" :  \"" << s_axi_CTRL_BUS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_BUS_WREADY\" :  \"" << s_axi_CTRL_BUS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_BUS_WDATA\" :  \"" << s_axi_CTRL_BUS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_BUS_WSTRB\" :  \"" << s_axi_CTRL_BUS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_BUS_ARVALID\" :  \"" << s_axi_CTRL_BUS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_BUS_ARREADY\" :  \"" << s_axi_CTRL_BUS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_BUS_ARADDR\" :  \"" << s_axi_CTRL_BUS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_BUS_RVALID\" :  \"" << s_axi_CTRL_BUS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_BUS_RREADY\" :  \"" << s_axi_CTRL_BUS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_BUS_RDATA\" :  \"" << s_axi_CTRL_BUS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_BUS_RRESP\" :  \"" << s_axi_CTRL_BUS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_BUS_BVALID\" :  \"" << s_axi_CTRL_BUS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_BUS_BREADY\" :  \"" << s_axi_CTRL_BUS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_BUS_BRESP\" :  \"" << s_axi_CTRL_BUS_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_AWVALID\" :  \"" << m_axi_mem_AWVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_mem_AWREADY\" :  \"" << m_axi_mem_AWREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_AWADDR\" :  \"" << m_axi_mem_AWADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_AWID\" :  \"" << m_axi_mem_AWID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_AWLEN\" :  \"" << m_axi_mem_AWLEN.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_AWSIZE\" :  \"" << m_axi_mem_AWSIZE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_AWBURST\" :  \"" << m_axi_mem_AWBURST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_AWLOCK\" :  \"" << m_axi_mem_AWLOCK.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_AWCACHE\" :  \"" << m_axi_mem_AWCACHE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_AWPROT\" :  \"" << m_axi_mem_AWPROT.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_AWQOS\" :  \"" << m_axi_mem_AWQOS.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_AWREGION\" :  \"" << m_axi_mem_AWREGION.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_AWUSER\" :  \"" << m_axi_mem_AWUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_WVALID\" :  \"" << m_axi_mem_WVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_mem_WREADY\" :  \"" << m_axi_mem_WREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_WDATA\" :  \"" << m_axi_mem_WDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_WSTRB\" :  \"" << m_axi_mem_WSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_WLAST\" :  \"" << m_axi_mem_WLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_WID\" :  \"" << m_axi_mem_WID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_WUSER\" :  \"" << m_axi_mem_WUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_ARVALID\" :  \"" << m_axi_mem_ARVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_mem_ARREADY\" :  \"" << m_axi_mem_ARREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_ARADDR\" :  \"" << m_axi_mem_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_ARID\" :  \"" << m_axi_mem_ARID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_ARLEN\" :  \"" << m_axi_mem_ARLEN.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_ARSIZE\" :  \"" << m_axi_mem_ARSIZE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_ARBURST\" :  \"" << m_axi_mem_ARBURST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_ARLOCK\" :  \"" << m_axi_mem_ARLOCK.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_ARCACHE\" :  \"" << m_axi_mem_ARCACHE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_ARPROT\" :  \"" << m_axi_mem_ARPROT.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_ARQOS\" :  \"" << m_axi_mem_ARQOS.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_ARREGION\" :  \"" << m_axi_mem_ARREGION.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_ARUSER\" :  \"" << m_axi_mem_ARUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_mem_RVALID\" :  \"" << m_axi_mem_RVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_RREADY\" :  \"" << m_axi_mem_RREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_mem_RDATA\" :  \"" << m_axi_mem_RDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_mem_RLAST\" :  \"" << m_axi_mem_RLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_mem_RID\" :  \"" << m_axi_mem_RID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_mem_RUSER\" :  \"" << m_axi_mem_RUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_mem_RRESP\" :  \"" << m_axi_mem_RRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_mem_BVALID\" :  \"" << m_axi_mem_BVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_mem_BREADY\" :  \"" << m_axi_mem_BREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_mem_BRESP\" :  \"" << m_axi_mem_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_mem_BID\" :  \"" << m_axi_mem_BID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_mem_BUSER\" :  \"" << m_axi_mem_BUSER.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

